using System;
using BeatSaberMarkupLanguage;
using BeatSaberMarkupLanguage.Attributes;
using HMUI;
using PlaylistManager.AffinityPatches;
using PlaylistManager.Utilities;
using SiraUtil.Affinity;
using UnityEngine;
using UnityEngine.UI;
using Zenject;

namespace PlaylistManager.UI
{
    /// <summary>
    /// Adds vertical controls to the playlist grid when an accessibility column
    /// limit smaller than the game's default is selected.
    /// </summary>
    /// <remarks>
    /// The scroll-view integration was inspired by the OldPlaylist mod created by xlzs0.
    /// </remarks>
    internal sealed class PlaylistGridScrollController : IInitializable, IDisposable, IAffinity
    {
        private const float ScrollControlMargin = 1f;
        private const string ScrollControlsBsml =
            "<vertical id='vertical' horizontal-fit='PreferredSize' vertical-fit='PreferredSize' " +
            "anchor-pos-x='32' anchor-pos-y='-25' pref-height='75' pref-width='8'>\n" +
            "<scroll-view id='scroll-view'/>\n" +
            "</vertical>";

        private readonly AnnotatedBeatmapLevelCollectionsViewController _viewController;
        private readonly AnnotatedBeatmapLevelCollectionsUIPatches _gridPatches;
        private readonly IVRPlatformHelper _platformHelper;
        private readonly BSMLParser _bsmlParser;

        private AnnotatedBeatmapLevelCollectionsGridView _gridView;
        private AnnotatedBeatmapLevelCollectionsGridViewAnimator _gridViewAnimator;
        private PlaylistGridScrollView _gridScrollView;
        private Transform _scrollBar;
        private bool _pageControlWasActive;
        private bool _pageControlStateCaptured;
        private bool _isParsingControls;

        [UIComponent("scroll-view")]
        private ScrollView _bsmlScrollView;

        [UIComponent("vertical")]
        private RectTransform _vertical;

        private bool ScrollingEnabled => _gridPatches.VerticalScrollingEnabled;

        internal PlaylistGridScrollController(
            AnnotatedBeatmapLevelCollectionsViewController viewController,
            AnnotatedBeatmapLevelCollectionsUIPatches gridPatches,
            IVRPlatformHelper platformHelper,
            BSMLParser bsmlParser)
        {
            _viewController = viewController;
            _gridPatches = gridPatches;
            _platformHelper = platformHelper;
            _bsmlParser = bsmlParser;
        }

        public void Initialize()
        {
            CacheGridReferences();

            _viewController.didOpenBeatmapLevelCollectionsEvent += HandleGridOpened;
            _viewController.didCloseBeatmapLevelCollectionsEvent += HandleGridClosed;
        }

        public void Dispose()
        {
            _viewController.didOpenBeatmapLevelCollectionsEvent -= HandleGridOpened;
            _viewController.didCloseBeatmapLevelCollectionsEvent -= HandleGridClosed;
        }

        [AffinityPatch(typeof(AnnotatedBeatmapLevelCollectionsGridViewAnimator), nameof(AnnotatedBeatmapLevelCollectionsGridViewAnimator.Init))]
        [AffinityPostfix]
        private void HandleGridInitialized(AnnotatedBeatmapLevelCollectionsGridViewAnimator __instance)
        {
            CacheGridReferences();
            if (!ReferenceEquals(__instance, _gridViewAnimator))
            {
                return;
            }

            if (!ScrollingEnabled)
            {
                DisableScrolling();
                return;
            }

            _gridView._pageControl.gameObject.SetActive(false);

            if (_gridScrollView != null)
            {
                PositionScrollControls();
                _gridScrollView.RefreshLayout();
                return;
            }

            if (!_isParsingControls)
            {
                _isParsingControls = true;
                _bsmlParser.Parse(ScrollControlsBsml, _viewController.gameObject, this);
            }
        }

        [UIAction("#post-parse")]
        private void PostParse()
        {
            _isParsingControls = false;

            var viewport = _gridViewAnimator._viewportTransform;
            var content = _gridViewAnimator._contentTransform;
            content.localPosition = Vector3.zero;

            _scrollBar = _bsmlScrollView.transform.Find("ScrollBar");
            if (_scrollBar == null)
            {
                Plugin.Log.Error("Could not find the playlist grid scroll bar generated by BSML.");
                return;
            }

            var pageUpButton = _bsmlScrollView._pageUpButton;
            var pageDownButton = _bsmlScrollView._pageDownButton;
            var verticalScrollIndicator = _bsmlScrollView._verticalScrollIndicator;

            // Place the top button one full playlist row below the surrounding menu.
            _vertical.anchoredPosition += new Vector2(0f, -_gridView.cellHeight);

            _scrollBar.SetParent(_vertical);
            // The viewport masks overflowing playlist rows. Keep the controls beside
            // that mask rather than inside it, otherwise lowering them clips them too.
            _vertical.SetParent(viewport.parent, true);
            _vertical.SetAsLastSibling();
            _vertical.gameObject.SetActive(true);
            _scrollBar.gameObject.SetActive(false);
            PositionScrollControls();

            // The temporary BSML ScrollView only supplies the game's standard controls.
            // The actual scrolling component must live beside the native grid animator.
            UnityEngine.Object.Destroy(_bsmlScrollView.gameObject);

            var gridGameObject = _gridView.gameObject;
            gridGameObject.SetActive(false);

            if (gridGameObject.GetComponent<EventSystemListener>() == null)
            {
                gridGameObject.AddComponent<EventSystemListener>();
            }

            _gridScrollView = gridGameObject.AddComponent<PlaylistGridScrollView>();
            _gridScrollView.Initialize(viewport, content, pageUpButton, pageDownButton, verticalScrollIndicator);

            ScrollView scrollView = _gridScrollView;
            Accessors.PlatformHelperAccessor(ref scrollView) = _platformHelper;

            gridGameObject.SetActive(true);
            _gridScrollView.enabled = false;
            _gridScrollView.RefreshLayout();
        }

        private void HandleGridOpened()
        {
            if (!ScrollingEnabled || _gridScrollView == null)
            {
                DisableScrolling();
                return;
            }

            _gridView._pageControl.gameObject.SetActive(false);
            PositionScrollControls();
            _vertical.SetAsLastSibling();
            _vertical.gameObject.SetActive(true);
            _scrollBar.gameObject.SetActive(true);
            _gridScrollView.Open();
        }

        private void HandleGridClosed()
        {
            if (_scrollBar != null)
            {
                _scrollBar.gameObject.SetActive(false);
            }

            if (_gridScrollView != null)
            {
                _gridScrollView.Close();
            }
        }

        private void DisableScrolling()
        {
            if (_gridView != null)
            {
                _gridView._pageControl.gameObject.SetActive(_pageControlWasActive);
            }

            if (_scrollBar != null)
            {
                _scrollBar.gameObject.SetActive(false);
            }

            if (_gridScrollView != null)
            {
                _gridScrollView.Close();
            }
        }

        private void CacheGridReferences()
        {
            if (_gridView == null)
            {
                _gridView = _viewController._annotatedBeatmapLevelCollectionsGridView;
                _gridViewAnimator = _gridView._animator;
            }

            if (!_pageControlStateCaptured)
            {
                _pageControlWasActive = _gridView._pageControl.gameObject.activeSelf;
                _pageControlStateCaptured = true;
            }
        }

        private void PositionScrollControls()
        {
            if (_vertical == null || _vertical.parent == null || _gridView == null)
            {
                return;
            }

            var controlsParent = _vertical.parent;
            var rightmostCellEdge = float.NegativeInfinity;
            foreach (var component in _gridView._gridView.cellsEnumerator)
            {
                if (component == null
                    || !component.gameObject.activeInHierarchy
                    || component.transform is not RectTransform cellTransform)
                {
                    continue;
                }

                var cellBounds = RectTransformUtility.CalculateRelativeRectTransformBounds(
                    controlsParent,
                    cellTransform);
                rightmostCellEdge = Mathf.Max(rightmostCellEdge, cellBounds.max.x);
            }

            if (float.IsNegativeInfinity(rightmostCellEdge))
            {
                return;
            }

            var controlBounds = RectTransformUtility.CalculateRelativeRectTransformBounds(
                controlsParent,
                _vertical);
            var localPosition = _vertical.localPosition;
            localPosition.x += rightmostCellEdge + ScrollControlMargin - controlBounds.min.x;
            _vertical.localPosition = localPosition;
        }

        [AffinityPatch(typeof(ScrollView), "UpdateVerticalScrollIndicator")]
        [AffinityPrefix]
        private bool UpdateVerticalScrollIndicator(ScrollView __instance, float posY)
        {
            if (__instance is not PlaylistGridScrollView gridScrollView)
            {
                return true;
            }

            gridScrollView.UpdateGridScrollIndicator(posY);
            return false;
        }

        [AffinityPatch(typeof(ScrollView), nameof(ScrollView.UpdateContentSize))]
        [AffinityPrefix]
        private bool UpdateContentSize(ScrollView __instance)
        {
            if (__instance is not PlaylistGridScrollView gridScrollView)
            {
                return true;
            }

            gridScrollView.UpdateGridContentSize();
            return false;
        }

        [AffinityPatch(typeof(ScrollView), "SetDestinationPos")]
        [AffinityPrefix]
        private bool SetDestinationPosition(ScrollView __instance, float value)
        {
            if (__instance is not PlaylistGridScrollView gridScrollView)
            {
                return true;
            }

            gridScrollView.SetGridDestinationPosition(value);
            return false;
        }

        [AffinityPatch(typeof(ScrollView), "RefreshButtons")]
        [AffinityPrefix]
        private bool RefreshButtons(ScrollView __instance)
        {
            if (__instance is not PlaylistGridScrollView gridScrollView)
            {
                return true;
            }

            gridScrollView.RefreshGridButtons();
            return false;
        }
    }
}
